### ISSUE TITLE
Update shared library name due GeographicLib 2.0

### ISSUE THREAD

**Issue by AchmadFathoni** [ros-noetic-arch/ros-noetic-libmavconn#3]
According to [changelog](https://geographiclib.sourceforge.io/C++/doc/changes.html), library file now called libGeographicLib.so, etc., instead of libGeographic.so. Fixed with #2

**Comment by acxz** [comment]
This error is tracked in the repo, where the build issue occurs: https://github.com/ros-noetic-arch/ros-noetic-mavros/issues/3
